import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const USER_ID = "cmo3u49er0000ajkml31233ao";

const briefs = [
  {
    title: "Liquid Death at the Maut Ka Kua",
    category: "INDIAN_FESTIVAL" as const,
    protagonistArchetype: "Male, 35, Rajasthani, worn leather jacket, mirror-work boots, on Royal Enfield Bullet 350",
    environment: "Wall of Death silodrome interior, 8m diameter cedar barrel, Rajasthan mela, 3pm October",
    productFamily: "Liquid Death",
    productIntegration: "HELD" as const,
    headline: "Maut Ka Kua",
    subhead: "Murder Your Thirst",
    notes: `Wall of Death silodrome interior — circular wooden barrel 8 meters in diameter, 5 meters tall, constructed from vertical deodar cedar planks, each plank 20cm wide with visible saw kerf marks, the lower third darkened by motor oil saturation. Gaps between planks reveal slivers of bright Rajasthan sky. Crowd at the upper rim, 3–4 people deep, hands gripping the top rail, faces focused on the spectacle below, none looking at the camera. Protagonist: male, 35, Rajasthani, deep brown skin with a fine layer of desert dust, wearing a worn leather jacket with visible creases at the elbows, ox-blood color, and a faded denim shirt beneath. Bootleg Levi's 501 jeans with mechanical wear at the knees, steel-toe boots with a band of Rajasthani mirror-work across the toe cap. He sits on a Royal Enfield Bullet 350, right hand holding a Liquid Death can at chest height, grip relaxed, condensation visible on the can. Left hand rests on the handlebar. Expression: jaw forward, eyes focused slightly left of frame. Environment: 3pm, October, Rajasthan mela — Ferris wheel visible through crowd gaps, hand-painted Hindi signage in the background. Light: direct sun at 45 degrees from camera-right, 5800K, hard shadows with 2cm penumbra. Camera: 35mm lens, f/2.8, photographer on the barrel floor, camera at 1.4m height, 12-degree upward angle. Kodak Portra 800 pushed one stop. Cedar plank grain and chrome engine casing show wear and polish. Atmospheric: suspended dust catching the sun shaft, diesel exhaust pooling at ground level, creating a faint haze.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no stock photography lighting, no smiling at camera, no composite look`,
  },
  {
    title: "Suburban dad knight in the cereal aisle",
    category: "ABSURDIST_WESTERN" as const,
    protagonistArchetype: "Middle-aged American dad, 45, Caucasian, full plate armor, khaki shorts below knee cops",
    environment: "Big-box grocery store cereal aisle, 20m long, steel shelving 2.5m high, fluorescent 4000K",
    productFamily: "sparkling water",
    productIntegration: "HELD" as const,
    headline: "Every Aisle Is a Quest",
    subhead: null,
    notes: `Big-box grocery store, cereal aisle — wide shot capturing the full expanse of the aisle, 20 meters long, 3 meters wide, with steel shelving units on both sides reaching 2.5 meters high. Shelves stocked with colorful cereal boxes in a mix of primary colors and cartoon mascots, creating a vibrant visual cacophony. Linoleum floor in a neutral grey pattern, showing scuff marks from shopping carts and foot traffic. Overhead fluorescent lighting, 4000K, casting a uniform, shadowless light across the scene. Protagonist: middle-aged American dad, 45, Caucasian, clad in full plate armor — brushed steel with no visible wear, pristine and reflective, capturing the store's fluorescent lights in smooth highlights. Armor includes a helmet with visor up, revealing a clean-shaven face with a focused expression, eyes scanning the cereal boxes. Right hand holds a can of sparkling water at chest height, fingers relaxed around the can, label facing outward, condensation beads on the can's surface catching the light. Left hand rests on the hilt of a sheathed sword at his side, the sword's pommel glinting under the store lights. Attire beneath the armor: khaki shorts visible below the knee cops, paired with white athletic socks and sneakers. Environment: a woman in casual attire, 10 meters down the aisle, browsing the shelves, oblivious to the knight. A stock clerk restocking shelves at the far end, focused on his task, not acknowledging the protagonist. Camera: 35mm lens, f/5.6, positioned at eye level, capturing the full length of the aisle and the protagonist occupying the right third of the frame.\n\nNegative: no rendered text, no watermarks, no logo overlays, no AI artifacts, no melted hands, no warped anatomy, no cinematic lighting, no posed expression, no reactions from bystanders, no dramatic camera angles`,
  },
  {
    title: "Japanese whisky bar golden hour",
    category: "PREMIUM_LIFESTYLE" as const,
    protagonistArchetype: "Japanese male, early 50s, salt-and-pepper hair, charcoal grey wool suit, slim fit",
    environment: "Mid-century Tokyo whisky bar, Ginza, teak paneling, November 6:30pm",
    productFamily: null,
    productIntegration: "HELD" as const,
    headline: "The Last Pour Before Dark",
    subhead: null,
    notes: `Mid-century Tokyo whisky bar, Ginza, November, 6:30pm. Protagonist: Japanese male, early 50s, deep-set eyes, high cheekbones, skin with a fine texture and slight sheen from natural oils, hair salt-and-pepper, neatly combed back. Attire: charcoal grey wool suit, slim fit, single-breasted with notch lapels, subtle pinstripe pattern, white dress shirt with a narrow spread collar, no tie. Cuff visible, buttoned, no cufflinks. A single brushed-silver watch on the left wrist, minimalist face, black leather strap. Expression: focused, eyes slightly narrowed, assessing the whisky's color and clarity, not performing for the camera. Environment: bar interior with teak paneling, warm amber hue, polished to a soft sheen. Back bar lined with premium Japanese whisky bottles, labels facing forward, handwritten Japanese tags on necks. Light: golden-hour sunlight entering through a west-facing window, casting a warm 3200K glow across the bar, illuminating the protagonist's face and the whisky glass he holds. Incandescent overhead light at 2800K providing a soft fill, creating a gentle shadow under his chin and nose. Camera: 50mm lens, f/2.8, focus on the protagonist's face, background softly blurred. Framed at 2/3 height, capturing face and upper body, whisky glass held in right hand at chest height, glass rim catching the light, whisky amber (#C47A3A) glowing. Surface materials: teak bar top, interlocked grain visible, polished high points with diffuse low points. Whisky glass: 3mm thick, condensation on lower third, droplets catching light. Atmosphere: slight haze from ambient humidity and absorbed cigarette smoke, softening shadows and adding warmth. No other patrons visible, creating an intimate, focused scene.\n\nNegative: no rendered text, no watermarks, no logo overlays, no AI artifacts, no melted hands, no warped anatomy, no Western bar aesthetics, no generic mood lighting, no obvious product photography setup`,
  },
  {
    title: "Durga Puja evening crowd Kolkata",
    category: "INDIAN_FESTIVAL" as const,
    protagonistArchetype: "Bengali woman, early 30s, Tant saree off-white with red border, holding clay diya",
    environment: "North Kolkata lane, colonial-era buildings, Durga Puja pandal archway, 6pm October",
    productFamily: null,
    productIntegration: "ABSENT" as const,
    headline: "Shubho Bijoya",
    subhead: null,
    notes: `North Kolkata lane, 6pm, October. The lane is narrow, flanked by colonial-era buildings with weathered lime plaster facades, patches of exposed red brick visible where the plaster has crumbled away. A Durga Puja pandal entrance is visible in the background, intricately decorated with jute and bamboo, the archway adorned with marigold garlands. Strings of incandescent bulbs, 2700K, hang overhead, casting a warm glow across the scene, creating a festive atmosphere. The ground is a mix of cobblestones and packed earth, showing signs of recent rain with small puddles reflecting the warm light. Protagonist: Bengali woman, early 30s, medium brown skin with warm undertones, wearing a traditional Tant saree. The saree is off-white with a red border (#C8102E), the weave pattern visible in the light, showing a fine cotton texture with a matte finish. Her hair is neatly tied back in a bun, adorned with a single jasmine flower. She stands with a slight lean to her left, her right hand resting on her hip, left hand holding a small clay diya, its flame flickering gently. Expression: serene focus on the diya, not acknowledging the camera, embodying the reverence of the moment. Environment: bustling crowd fills the lane, people of various ages, men in kurta-pajamas, women in colorful sarees, children running, their laughter mingling with the distant sound of dhak drums from the pandal. Camera: 35mm lens, f/4, capturing the depth of the scene, focus on the protagonist with the crowd and pandal entrance in soft focus. Camera is at eye-level, 1.6 meters from the ground.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no studio background, no posed expressions, no empty streets, no modern clothing`,
  },
  {
    title: "Kinfolk breakfast, Oslo apartment",
    category: "PREMIUM_LIFESTYLE" as const,
    protagonistArchetype: "Scandinavian woman, 32, hands only, grey cashmere sweater, silver ring",
    environment: "Oslo apartment kitchen, birch plywood cabinetry, Carrara marble counter, 8am October overcast",
    productFamily: null,
    productIntegration: "HELD" as const,
    headline: "Still Morning",
    subhead: null,
    notes: `Oslo apartment kitchen, minimalist Scandinavian design — birch plywood cabinetry with visible edge banding, matte finish, a single open shelf with ceramic mugs and a small potted plant in a white stoneware pot. Kitchen counter: honed Carrara marble, white with subtle grey veining (#E0E0E0), a single espresso cup and saucer set in matte white porcelain, the cup half-full with a rich dark espresso, crema visible as a 3mm layer with a slight swirl pattern from the pour. Protagonist: hands only, Scandinavian woman, 32, fair skin with cool undertones, no visible veins, nails trimmed short, natural finish. Right hand holds the espresso cup by the handle, thumb and index finger pinching delicately, the saucer resting on the counter. Left hand rests on the counter, fingers relaxed, a simple silver band on the ring finger, brushed finish. Attire: soft grey cashmere sweater sleeve visible at the wrist, ribbed cuff, subtle pilling indicating wear. Environment: overcast October morning, 8am, light entering through a large east-facing window, diffused by sheer white linen curtains. Window frame visible in background, painted in muted sage green (#9BAA8F), slightly chipped at the corners. Light: soft diffused daylight, 6500K, filling the room with a gentle cool ambiance, no harsh shadows. Camera: 50mm lens at f/1.8, focus on the espresso cup, hands and background softly blurred. Shot from slight elevation, looking down at a 20-degree angle.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no harsh lighting, no cluttered background, no visible face, no dramatic shadows`,
  },
  {
    title: "Chai wallah at Howrah station at 5am",
    category: "INDIAN_FESTIVAL" as const,
    protagonistArchetype: "Male chai wallah, 55, Bihari, faded olive kurta, maroon paisley shawl",
    environment: "Howrah Railway Station platform 7, pre-dawn 5am, winter, sodium vapor 2100K",
    productFamily: null,
    productIntegration: "HELD" as const,
    headline: "Pehli Chai",
    subhead: null,
    notes: `Howrah Railway Station platform 7, pre-dawn, 5am, winter. Platform surface: smooth concrete with decades of foot traffic polish, scattered with small patches of coal dust and morning dew, reflecting the dim station lights. Background: blurred outlines of waiting trains, their steel surfaces catching the faintest hint of sodium vapor lighting at 2100K, creating a warm glow against the cold morning air. Protagonist: male chai wallah, 55, Bihari, dark brown skin with a deep network of fine lines and creases from years of outdoor work, skin texture visible at the temples, natural oils catching the pre-dawn sidelight. Expression: focused, eyes slightly narrowed, lips pursed in concentration as he pours chai. Attire: faded olive-green kurta, medium-weight cotton, threadbare at the elbows, a small tear at the left shoulder seam, layered over a white thermal undershirt visible at the neckline. A woolen shawl draped over his shoulders, maroon with a subtle paisley pattern, slightly frayed at the edges. Product: clay kulhad held in his right hand at chest height, thumb and forefinger cradling the rim, steam rising visibly in the cold air, chai level 1cm below the rim. Left hand holds a stainless steel kettle, polished from use, spout angled precisely at the kulhad, chai mid-pour, a thin stream creating a frothy surface. Light: dim station sodium vapor at 2100K, key light on the protagonist's face from a station lamp 3 meters to the left. Camera: 50mm lens, f/1.8, focus locked on the chai kulhad, protagonist's face in soft focus, background dissolving into bokeh at 2 meters.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no studio background, no posed expression, no modern plastic cups`,
  },
  {
    title: "Office worker samurai defending the printer",
    category: "ABSURDIST_WESTERN" as const,
    protagonistArchetype: "Female, 38, Japanese, samurai armor over light blue business blouse and pencil skirt, geta sandals",
    environment: "Corporate office printer room, open-plan, slate grey carpet tiles, fluorescent 4000K, 2pm Tuesday",
    productFamily: "energy drink",
    productIntegration: "HELD" as const,
    headline: "Defend the Queue",
    subhead: null,
    notes: `Corporate office printer room, open-plan, 2pm Tuesday. Standard office layout: modular carpet tiles in slate grey (#4A4A4A), acoustic ceiling tiles, fluorescent tube lighting at 4000K — flat, even, zero atmosphere. Printer: large multifunction device, white plastic casing with a touchscreen interface, paper trays open, a stack of A4 paper slightly askew on the output tray. Protagonist: female, 38, Japanese, medium complexion with cool undertones, dark brown hair in a neat bun. Samurai armor: polished steel with no visible wear, no patina, no dents — factory-new appearance. Armor covers torso and shoulders, leaving arms free. Over the armor, a business casual blouse: light blue (#A3C1DA), cotton-poly blend, short sleeves, buttoned up to the collar, no visible creases. Black pencil skirt, knee-length, no visible seams or wear. Feet in traditional Japanese geta sandals, pristine lacquer finish, no scuff marks. Expression: focused, eyes narrowed, right hand holding an energy drink can at chest height, label facing camera — matte black with a vibrant green logo, condensation beads on the surface, hand grip firm but not crushing. Left hand on the printer's touchscreen, poised to navigate the interface. Environment: two coworkers visible in the background, seated at desks, typing on laptops, not acknowledging the samurai presence. Camera: 35mm lens, f/8, eye-level, 1.6m height, capturing the protagonist in the left third of the frame with the printer and office environment occupying the rest.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no dramatic lighting, no cinematic angles`,
  },
  {
    title: "Scandi ceramicist morning studio",
    category: "PREMIUM_LIFESTYLE" as const,
    protagonistArchetype: "Danish woman, 40, clay-stained hands, linen apron over navy shirt, hair in bun",
    environment: "Copenhagen ceramic studio, whitewashed brick, concrete floor, north-facing skylight 5500K, 9am March",
    productFamily: null,
    productIntegration: "PLACED" as const,
    headline: "Form Follows Morning",
    subhead: null,
    notes: `Copenhagen ceramic studio, 9am, March, overcast light. Studio interior: whitewashed brick walls with lime mortar, 3 meters tall, paint slightly chipped at the corners, revealing the original red brick. Concrete floor, smooth finish with a matte sealant, color #8D8D8D, visible wear paths from foot traffic and clay spills. North-facing skylight, 2 meters wide, 1 meter tall, diffusing soft, even light across the workspace — 5500K, no direct sun, shadow edges soft with a 5cm penumbra. Protagonist: Danish woman, 40, light complexion with cool undertones, fine lines at the corners of her eyes, evidence of years spent in focused work. Dark blonde hair, tied back in a practical bun, a few loose strands framing her face. Wearing a natural linen apron, oatmeal color (#D3C4A3), medium weight, with visible weave texture, tied at the back, clay smudges on the front. Underneath, a navy blue long-sleeve cotton shirt, slightly rolled sleeves, fabric showing a soft, broken-in drape. Hands: clay-stained, fingers coated in a thin layer of grey stoneware, nails short, practical. Expression: focused on shaping a clay vessel, eyes downcast, lips slightly parted in concentration. Product: Matcha set — chawan (tea bowl) and chasen (bamboo whisk) placed on a low wooden workbench, 1 meter from the protagonist, slightly off-center to the left. Camera: 50mm lens, f/4, positioned 1.5 meters from the protagonist, eye-level, capturing the scene with a slight downward angle to emphasize the workspace.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no studio lighting, no posed expression, no cluttered background`,
  },
  {
    title: "Holi powder explosion in an Ahmedabad lane",
    category: "INDIAN_FESTIVAL" as const,
    protagonistArchetype: "Teenage boy, 16, Gujarati, white kurta splattered with magenta, turquoise, saffron; bare feet",
    environment: "Narrow Ahmedabad pol lane, ornate wooden jharokhas, cobblestone, noon sun March 6000K",
    productFamily: null,
    productIntegration: "ABSENT" as const,
    headline: "Rang Barse",
    subhead: null,
    notes: `Narrow Ahmedabad pol lane, traditional Gujarati architecture — three-story buildings with ornate wooden jharokhas painted in faded turquoise (#3D9E9E), intricate latticework casting sharp shadows on the whitewashed walls. Lane width: 3 meters, cobblestone surface with irregular stones, some subsidence creating shallow puddles from recent water splashes. Noon sun, March, harsh light at 90 degrees, minimal shadow length, 6000K, hard-edged shadows with 1cm penumbra. Protagonist: teenage boy, 16, Gujarati, medium brown skin with warm undertones, fine pores visible on the forehead, natural oils catching the sidelight. Expression: mid-action, eyes focused on the target, mouth slightly open in concentration, not performing for the camera. Attire: white cotton kurta, lightweight, loose fit, with a faintly visible weave pattern, sleeves rolled to mid-forearm, splattered with vibrant Holi colors — magenta, turquoise, and saffron. Bottoms: faded denim jeans, relaxed fit, with frayed hems. Feet bare, dust and color powder visible on the toes and arches. Environment: behind the protagonist, a row of parked bicycles leaning against the wall, each with a splash of colors on the frames. To the left, a small shrine with marigold garlands and incense sticks, smoke curling upwards, catching the light. Camera: 35mm lens, f/8, positioned at 1.5m height, capturing the full scene with the protagonist in the lower third. Focus on the boy's hand mid-throw, with the color powder in sharp detail, background in graduated bokeh.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no studio background, no posed expression, no stock photography lighting`,
  },
  {
    title: "Retired accountant wizard at the DMV",
    category: "ABSURDIST_WESTERN" as const,
    protagonistArchetype: "Male, 67, Caucasian, deep indigo wizard robes, long white beard, bifocals, brown sandals",
    environment: "American DMV waiting room, faded blue plastic chairs, beige walls, fluorescent 4000K, 3pm Tuesday",
    productFamily: "Liquid Death",
    productIntegration: "HELD" as const,
    headline: "B42",
    subhead: "Your Number Will Be Called",
    notes: `American DMV waiting room, 3pm on a Tuesday — beige linoleum floor with scuff marks from years of foot traffic, a slight sheen from the overhead fluorescent lights. Rows of plastic chairs in faded blue (#4A90E2), molded for uncomfortable sitting, arranged in a grid pattern with 1 meter between rows. Walls painted in institutional off-white (#F5F5DC), a single wall clock with black numerals and hands, showing 3:15pm. Protagonist: male, 67, Caucasian, full wizard robes in deep indigo (#4B0082), fabric a heavy wool blend with a subtle herringbone pattern, no visible wear. Robe hem 2cm above the floor, revealing brown leather sandals, polished leather with no visible scuffs or wear. Long white beard, neatly combed, reaching mid-chest, no yellowing or fraying at the ends. Bifocal glasses with thin metal frames, perched on his nose, reflecting the fluorescent light as two parallel lines. Right hand holds a DMV number ticket, number 'B42' printed in large black font, held at chest height with a relaxed grip. Left hand holds a can of sparkling water, brand 'Liquid Death,' matte black can with condensation droplets visible, held at the waist level, fingers relaxed around the can. Expression: eyes scanning the room, not focused on any one thing, slightly furrowed brow as if in thought. Camera: 35mm lens, f/5.6, shot from eye-level at 1.6 meters height, capturing the protagonist in the left third of the frame with the waiting room extending into the background.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no posed expression, no studio background, no cinematic lighting, no dramatic angles`,
  },
  {
    title: "Italian nonna espresso ritual, Naples",
    category: "PREMIUM_LIFESTYLE" as const,
    protagonistArchetype: "Italian woman, 72, Neapolitan, floral apron over dark blue dress, silver-grey hair in bun",
    environment: "Neapolitan apartment kitchen, terrazzo floor, pale yellow walls, 7:30am October",
    productFamily: null,
    productIntegration: "ABSENT" as const,
    headline: "Ogni Mattina",
    subhead: null,
    notes: `Neapolitan apartment kitchen, early October morning, 7:30am. Kitchen: terrazzo floor in muted earth tones, polished with a subtle sheen, visible wear paths leading from the doorway to the stove. Walls: pale yellow (#F5E79E) with a matte finish, small cracks near the ceiling from settling over decades. Countertop: white Carrara marble with grey veining (#C0C0C0), polished but with slight etching from years of use. Protagonist: Italian woman, 72, Neapolitan, visible from the waist up. Skin: olive complexion with fine lines and age spots, hands slightly veined, nails neatly trimmed, no polish. Attire: classic floral apron over a dark blue dress (#2C3E50), apron fabric cotton with a fine weave, floral pattern in faded reds and greens, apron ties visible at the back. Hair: silver-grey, pulled back into a neat bun, a few loose strands framing the face. Expression: focused, eyes slightly squinted, lips pressed together in concentration as she pours espresso. Jewelry: simple gold wedding band, slightly worn, on left hand. Moka pot: stainless steel, well-used with a patina of coffee oils, resting on a small blue gas flame, steam rising from the spout. Espresso being poured into a small white ceramic cup with a single blue stripe around the rim, the coffee surface showing a light crema, steam curling upwards. Light: natural morning light from a window to the left, soft diffused shadows, 5200K. Camera: 50mm lens, f/4, capturing the nonna from waist up, focus on her hands and the espresso cup.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no modern kitchen appliances, no studio lighting, no posed expression, no cold light sources`,
  },
  {
    title: "Kalbelia dancer backstage Pushkar mela",
    category: "INDIAN_FESTIVAL" as const,
    protagonistArchetype: "Female, 24, Rajasthani, Kalbelia dancer, black embroidered dress with mirror work, silver jewelry",
    environment: "Backstage tent at Pushkar Camel Fair, canvas tarpaulin, compacted earth floor, 5pm sunlight",
    productFamily: null,
    productIntegration: "ABSENT" as const,
    headline: "Pehle Pardon Ke Peeche",
    subhead: null,
    notes: `Backstage tent at Pushkar Camel Fair, constructed from beige canvas tarpaulin stretched over bamboo poles, 3 meters tall, with visible patch repairs in darker khaki fabric (#8B7E66) at stress points. The canvas is translucent, allowing warm 5pm sunlight to filter through, creating a golden glow inside with soft diffused shadows. Ground is compacted earth, slightly uneven, with scattered straw and footprints indicating heavy foot traffic. Protagonist: female, 24, Rajasthani, Kalbelia dancer, medium brown skin with warm undertones, fine pores visible at the temples, natural oils catching the sidelight. Wearing a traditional Kalbelia dress: black cotton with bright pink and orange embroidery in geometric patterns, mirror work embedded in the fabric reflecting pinpoints of light. The skirt is full and gathered, reaching to the ankles, with a wide pink border (#E75480) at the hem. The blouse is fitted with long sleeves and a deep neckline, adorned with silver sequins. A black dupatta draped over her head, edged in silver thread, partially obscures her hair, which is braided with small silver bells woven in. Jewelry: large silver earrings and a necklace with multiple strands of small silver beads. Expression: eyes closed, head slightly tilted back, hands resting gently on her lap, fingers relaxed, not performing. Camera: 50mm lens, f/2.8, positioned at 1.5 meters from the subject, eye-level angle capturing her face and upper body, background softly out of focus.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no studio background, no posed expression, no composite look`,
  },
  {
    title: "Astronaut at a suburban backyard barbecue",
    category: "ABSURDIST_WESTERN" as const,
    protagonistArchetype: "NASA astronaut, EMU suit, helmet off, holding barbecue tongs; craft beer in left hand",
    environment: "Suburban backyard, Fourth of July BBQ, white picket fence, gas grill, 4pm direct sun 5800K",
    productFamily: "craft beer",
    productIntegration: "HELD" as const,
    headline: "T-Minus Burgers",
    subhead: null,
    notes: `Suburban backyard, Fourth of July BBQ, 4pm — a typical American suburban setting with a white picket fence in the background, 1.2 meters high, paint slightly chipped at the base, grass lawn with a mix of Kentucky bluegrass and perennial ryegrass, slightly overgrown to 6cm height. In the foreground, a NASA astronaut in a pristine EMU suit, helmet off, standing to the left of the frame. The suit is bright white with no visible wear, the fabric taut and clean, reflecting the afternoon sun. The astronaut is holding a pair of stainless steel barbecue tongs in the right hand, at waist height, relaxed grip, tongs open. The left hand holds a craft beer can, label facing away from the camera, condensation forming small beads on the can's surface, indicating coldness against the warm air. The astronaut's expression is focused on the grill, head slightly tilted down, eyes squinting against the sun. Behind the astronaut, an inflatable kiddie pool in bright blue (#0073CF), half-filled with water, a few plastic toys floating. A gas grill to the right of the astronaut, lid open, with visible grill marks on the cooking surface, a few burgers and hot dogs sizzling, smoke rising in thin wisps. The light is direct sunlight from the west, casting long shadows across the lawn, color temperature around 5800K. Camera: 28mm lens, f/8, positioned at 1.5 meters height, eye-level.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no posed expressions, no studio background, no cinematic lighting`,
  },
  {
    title: "Wabi-sabi flower arranger, Kyoto",
    category: "PREMIUM_LIFESTYLE" as const,
    protagonistArchetype: "Japanese woman, 58, indigo sashiko kimono, holding ikebana shears, low bun with wooden hairpin",
    environment: "Traditional Kyoto machiya workshop, tatami floor, shoji screens, south-facing window, November 2pm 4800K",
    productFamily: null,
    productIntegration: "ABSENT" as const,
    headline: "Ma",
    subhead: null,
    notes: `Traditional Kyoto machiya workshop, tatami-mat flooring with visible woven igusa grass texture, each mat 90cm wide, straw core giving slight spring underfoot. Sliding shoji screen doors with rice paper panels, wooden lattice in dark-stained cedar, open to reveal a single south-facing window. Window frame: unpainted hinoki cypress, 3cm wide, natural patina from sun exposure. November, 2pm — weak autumn sunlight casting a soft, diffused glow across the room, 4800K, creating gentle, elongated shadows on the tatami. Protagonist: Japanese woman, 58, seated on a zabuton cushion, posture erect yet relaxed, focused on the ikebana arrangement in progress. Skin: light olive with fine lines at the corners of her eyes and mouth, natural oils catching the side light, pores visible on her forehead. Hair: salt-and-pepper, gathered into a low bun secured with a simple wooden hairpin, no decorative elements. Attire: indigo-dyed cotton kimono, subtle sashiko stitching pattern, visible at 30cm distance, light sheen from the tightly woven fabric, sleeves neatly folded back to the wrist. Hands: deliberate, right hand holding a pair of ikebana shears with blackened steel blades, left hand gently adjusting the angle of a slender branch. Ikebana arrangement: asymmetrical, featuring a single branch of red maple, a sprig of white camellia, and a single stem of yellow chrysanthemum. Camera: 50mm lens, f/4, positioned at 1.5m height, capturing the full width of the room, protagonist in the left third of the frame.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no modern decor elements, no cluttered background, no artificial light sources, no posed expression`,
  },
  {
    title: "Beekeeper in a Mumbai rooftop colony",
    category: "OTHER" as const,
    protagonistArchetype: "Female, 34, Indian, beekeeper suit with veil half-lifted, gold hoop earrings, dark hair in bun",
    environment: "Mumbai highrise rooftop, 6am monsoon edge, three Langstroth hives, city skyline in morning haze",
    productFamily: null,
    productIntegration: "ABSENT" as const,
    headline: "Urban Colony",
    subhead: null,
    notes: `Mumbai highrise rooftop, 6am, monsoon edge. Rooftop surface: concrete with visible aggregate, slightly damp from morning dew, reflecting the soft light. Hives: three wooden Langstroth hives, painted in pastel shades — mint green, pale yellow, and sky blue, each 60cm tall, with the paint showing slight peeling at the edges. Positioned in the foreground, 2 meters apart, lids closed. Protagonist: female, 34, Indian, medium brown skin with warm undertones, visible through the half-veiled suit. Beekeeper suit: lightweight cotton blend, off-white with a slight sheen, veil partially lifted, revealing her face. Expression: serene, eyes focused on the hives, hands resting on the top of the nearest hive, fingers relaxed. Hair: dark, tied back in a low bun, a few strands escaping, catching the early morning light. Jewelry: simple gold hoop earrings, 2cm diameter, catching the light. Environment: Mumbai skyline in the background, highrises silhouetted against the morning haze, visibility reduced to 500m, creating a soft, diffused backdrop. Light: early morning sun, 6am, low on the horizon, casting long shadows, color temperature 5500K, soft with a warm tint. Camera: 35mm lens, f/4, positioned at 1.6m height, capturing the protagonist in the left third of the frame, with the hives and cityscape filling the rest.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no studio background, no posed expression, no dramatic lighting`,
  },
  {
    title: "Corporate warrior at a Kolkata pandal bhog",
    category: "INDIAN_FESTIVAL" as const,
    protagonistArchetype: "Male, 42, Bengali, business shirt and formal trousers, cross-legged on floor, Bluetooth earpiece",
    environment: "North Kolkata pandal interior, maroon and mustard drapes, red oxide floor, 7pm Navami, 2700K incandescent",
    productFamily: null,
    productIntegration: "ABSENT" as const,
    headline: "Navami Bhog",
    subhead: null,
    notes: `North Kolkata pandal interior, 7pm Navami evening — bamboo scaffolding structure with jute and cloth draping, dyed in deep maroon (#800000) and mustard yellow (#FFD700), forming a canopy over the devotees. The pandal floor: red oxide cement, polished to a sheen by decades of foot traffic, reflecting the warm glow of incandescent bulbs strung along the bamboo framework. Protagonist: male, 42, Bengali, medium brown skin with warm undertones, slight sheen from the evening humidity, wearing a light blue business shirt, slightly rumpled, sleeves rolled to the forearm, collar open, fabric showing light sweat patches at the back. Dark grey formal trousers, creased but showing signs of the day's wear at the knees and seat. Black leather shoes, lightly dusted with Kolkata's road dust, placed neatly beside him. Laptop bag: black ballistic nylon, resting on the floor to his right, zipper slightly open, a corner of a white paper document peeking out. Bluetooth earpiece in his left ear, small and discreet. Seated cross-legged on the floor, right hand reaching towards the banana leaf in front of him, fingers poised to scoop a portion of bhog — rice, dal, and a piece of fried fish visible, steam rising faintly. Camera: 24mm lens, f/4, positioned at a low angle, 30cm above the floor, capturing the protagonist and the bhog from a low perspective.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no studio background, no posed expression, no generic festival clichés`,
  },
  {
    title: "Minimalist Scandi morning, with a medieval blacksmith",
    category: "ABSURDIST_WESTERN" as const,
    protagonistArchetype: "Female, 34, Scandinavian, blacksmith leather apron over linen tunic, soot-marked forearms, pouring Chemex",
    environment: "Copenhagen apartment kitchen, 7am overcast, Carrara marble counter, Chemex brewing, small cast iron anvil",
    productFamily: null,
    productIntegration: "ABSENT" as const,
    headline: "Forge and Filter",
    subhead: null,
    notes: `Copenhagen apartment kitchen, 7am, overcast light filtering through a north-facing window, 5500K color temperature, soft and diffuse with no direct sun. Carrara marble countertop, polished finish, light grey veining across a white base (#F5F5F5), the surface reflecting the soft ambient light. Chemex coffee maker mid-brew, glass carafe with a wooden collar and leather tie, placed centrally on the countertop, coffee dripping from the filter into the carafe, visible steam rising faintly. Next to it, a small 15cm anvil, cast iron with a flat top and horn, no visible wear or marks. Protagonist: female, 34, Scandinavian, fair complexion with cool undertones, freckles scattered across the nose and cheeks. Hair tied back in a practical bun, no loose strands. Traditional blacksmith leather apron, chestnut brown, no visible creases or wear, over a natural linen tunic, off-white (#EAE6DA), loose fit with rolled sleeves to the elbows. Forearms visibly muscular, soot-marked — a fine layer of soot dust, not streaks, evenly distributed. Expression: focused on pouring coffee from the Chemex into a simple white ceramic mug, right hand steady, left hand supporting the carafe's base. Camera: 50mm lens, f/5.6, eye-level, 1.5m from the countertop, capturing the protagonist in the right third of the frame, Chemex and anvil in the left two-thirds.\n\nNegative: no rendered text, no watermarks, no logo overlays, no UI elements, no AI artifacts, no melted hands, no warped anatomy, no dramatic lighting, no cinematic angles, no posed expressions`,
  },
  {
    title: "South Indian filter coffee, brass and sunlight",
    category: "PREMIUM_LIFESTYLE" as const,
    protagonistArchetype: "Tamil woman, early 60s, Madisar saree, thin gold jhimki earrings, single plait, pouring filter coffee",
    environment: "Chettinad house interior, Tamil Nadu, red oxide floor, Burma teak pillars, 7am sunlight 3200K",
    productFamily: null,
    productIntegration: "ABSENT" as const,
    headline: "Kaapi",
    subhead: null,
    notes: `Chettinad house interior, Tamil Nadu, 7am. Red oxide floor, polished to a soft sheen, reflecting the morning light in diffuse patches, color #A52A2A. Carved Burma teak pillars, aged to a deep brown (#4B3621), with intricate floral patterns and geometric carvings, catching the light on their high points. A small enclosed courtyard visible through an open doorway, framed by the teak pillars, with a single potted jasmine plant in bloom, white flowers stark against the dark green leaves. Protagonist: Tamil woman, early 60s, wearing a cotton Madisar saree, faded cream with a subtle woven pattern, the pleats neatly arranged, fabric weight light, matte finish. Thin gold jhimki earrings, polished but not reflective, catching the sidelight. Hair in a single plait, black with strands of grey, neatly tied at the end with a simple black band. Expression: focused on the act of pouring, eyes following the stream of coffee. On a wooden table: a brass tumbler-dabarah set, brass polished to a soft glow, no visible tarnish, the tumbler positioned directly under the stream of coffee being poured from the dabarah, creating a long, unbroken arc. Steam rising from the coffee, visible in the morning light, creating a gentle haze around the top of the tumbler. Light: 7am sunlight entering from a high window, 45-degree angle, creating a warm 3200K glow. Camera: 50mm lens, f/4, focus on the brass tumbler, capturing the detail of the pouring stream and steam. Medium format simulation, Fuji Velvia 50 character.\n\nNegative: no rendered text, no watermarks, no logo overlays, no AI artifacts, no melted hands, no warped anatomy, no studio background, no posed expression, no modern kitchen elements, no cold light sources`,
  },
];

async function main() {
  console.log(`Seeding ${briefs.length} briefs for user ${USER_ID}...`);

  for (const b of briefs) {
    const created = await prisma.brief.create({
      data: {
        userId: USER_ID,
        title: b.title,
        category: b.category,
        protagonistArchetype: b.protagonistArchetype,
        environment: b.environment,
        productFamily: b.productFamily ?? null,
        productIntegration: b.productIntegration,
        headline: b.headline,
        subhead: b.subhead ?? null,
        notes: b.notes,
      },
    });
    console.log(`  ✓ ${created.id.slice(0, 8)} — ${created.title}`);
  }

  console.log("Done.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
